Fix for debugging on the runner (see below)
  * The following error does not appear on the local, but appears on the workflow
```
Traceback (most recent call last):
  File "/home/runner/work/autoware_dummy_repository/autoware_dummy_repository/create_prs_for_vcs_repositories_update.py", line 309, in <module>
    create_version_update_pr(args)
  File "/home/runner/work/autoware_dummy_repository/autoware_dummy_repository/create_prs_for_vcs_repositories_update.py", line 274, in create_version_update_pr
    repo.git.commit(m=commit_message, s=True)
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/git/cmd.py", line 986, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/git/cmd.py", line 1598, in _call_process
    return self.execute(call, **exec_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/git/cmd.py", line 1388, in execute
    raise GitCommandError(redacted_command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git commit -m feat(autoware.repos): update autowarefoundation/autoware_common to v1.0 -s
  stdout: 'On branch feat/update-autowarefoundation/autoware_common/v1.0
nothing to commit, working tree clean'
```

Signed-off-by: Junya Sasaki <junya.sasaki@tier4.jp>